### ISSUE TITLE
@Pass注解在GET请求下URL为api/xxx形式下失效

### ISSUE THREAD

**Issue by zhengmingze** [qq53182347/liugh-parent#1]
如图，
![image](https://user-images.githubusercontent.com/17629947/40112620-3a21de26-5939-11e8-95a3-0d3ae322652b.png)

![image](https://user-images.githubusercontent.com/17629947/40112614-328f8ec4-5939-11e8-8f73-16a82c6f9ca9.png)
Postman
![image](https://user-images.githubusercontent.com/17629947/40112649-4e06a14c-5939-11e8-9361-e03186aaf98b.png)

**Comment by qq53182347** [comment]
已经修改,感谢提出

**Comment by xiaofan1234** [comment]
![image](https://user-images.githubusercontent.com/45651646/55532672-55e1c300-56e1-11e9-873a-8b379b079ff4.png)
返回400
