### ISSUE TITLE
shiro UnauthorizedException 全局异常捕获不了，知道怎么解决吗？

### ISSUE THREAD

**Issue by fw19940314** [qq53182347/liugh-parent#13]
com.liugh.exception.UnauthorizedException: Username or password error
at com.liugh.shiro.MyRealm.doGetAuthenticationInfo(MyRealm.java:105)

**Comment by qq53182347** [comment]
实现 ResponseBodyAdvice重写 beforeBodyWrite方法试试

**Comment by qq53182347** [comment]
或者实现HandlerExceptionResolver重写resolveException方法
