### ISSUE TITLE
springboot打成jar包部署到linux上面,如果controller包含多个子包，pass加载有问题

### ISSUE THREAD

**Issue by myq3636** [qq53182347/liugh-parent#14]
controller目录结构如果有多个子目录，如下所示
----controller
----controller.client
----------------ClientController.java
----controller.admin
----------------AdminController.java

在本地运行时没有问题，打成jar包部署到linux机器上时，执行nohup java -jar liugh-web.jar &启动是，ClientController里面的pass方法没有加载成功。

**Comment by qq53182347** [comment]
没有复现问题 
![image](https://user-images.githubusercontent.com/29403761/61182014-45d26b80-a660-11e9-9808-dc74955440df.png)
