### ISSUE TITLE
REST接口 GET请求下无法获取到参数

### ISSUE THREAD

**Issue by ProYI** [qq53182347/liugh-parent#19]
`获取验证码接口``/smsVerify/{smsType}/{mobile}`  
这个接口时发现日志切面`RecordLogAspect`文件的156行因为无法获取到方法参数而抛出java.lang.StringIndexOutOfBoundsException: String index out of range: -1  
![GET Restful参数为空](https://user-images.githubusercontent.com/26431420/54480511-6fbb8300-4864-11e9-9b72-7056612adf1f.png)    
`接口出现严重异常：String index out of range: -1`
搜索后是get方式不带请求体，所以request.getParameterMap()获取的是url中`？`之后的参数，这样就导致`sb.deleteCharAt(sb.length()-1).toString()`角标越界了，我将请求方式修改为Post方法没有问题  
请教一下，在GET请求方式下这种情况怎么处理？

**Comment by giveme0101** [comment]
![image](https://user-images.githubusercontent.com/40479338/55706914-f8b57c80-5a14-11e9-8f8a-fce237511772.png)
主要原因是请求参数在path路径上导致获取参数越界，这样处理就可以了
