### ISSUE TITLE
为什么登录会报错

### ISSUE THREAD

**Issue by xiaofan1234** [qq53182347/liugh-parent#20]
![image](https://user-images.githubusercontent.com/45651646/55643432-aeaa7c00-5805-11e9-9826-a4d61bc85d17.png)

**Comment by biiliwuiid** [comment]
![image](https://user-images.githubusercontent.com/17468983/57903445-af244100-78a0-11e9-9c25-b281051f4cea.png)

**Comment by wangcan516** [comment]
一样的情况，postman和swagger都登录不了

**Comment by wangcan516** [comment]
解决了，是因为启动的时候MyCommandLineRunner报错，然后我注释掉重新启动后，就登录不了了。我发现项目存到有中文字幕的目录，启动项目MyCommandLineRunner就报错

**Comment by qq53182347** [comment]
问题得到解决就好

**Comment by gaohanghang** [comment]
感谢，同样遇到了这个问题
