### ISSUE TITLE
为什么没有提供前端界面

### ISSUE THREAD

**Issue by biiliwuiid** [qq53182347/liugh-parent#21]
很多功能没有界面展示

**Comment by ilaotan** [comment]
很多功能？ 有前端界面？？？

**Comment by eason1314** [comment]
完全没有页面

**Comment by baymax55** [comment]
没发现页面，只有返回json文件

**Comment by qq53182347** [comment]
不会前端，你们谁可以搞一下 我放你们的连接 用AngularJS或者VUEJS或者React都行

**Comment by itshu** [comment]
我可以提供给你一套vuejs的界面，跟你的后台是匹配的，只有权限管理的相关功能

**Comment by ZiHaoRan** [comment]
这个是前后端分离的项目，项目完全是后段代码，所以没有页面的

**Comment by qgh123456** [comment]
希望哪位大神能够提供一个前端页面，这个框架搭的可以

**Comment by qq53182347** [comment]
> 我可以提供给你一套vuejs的界面，跟你的后台是匹配的，只有权限管理的相关功能

你qq留一下，详谈可好

**Comment by itshu** [comment]
276537970

**Comment by StarIL** [comment]
> > 我可以提供给你一套vuejs的界面，跟你的后台是匹配的，只有权限管理的相关功能
> 
> 你qq留一下，详谈可好

有后续吗，需要对应匹配的后端。同求

**Comment by ysfcore** [comment]
密码更改之后运行报错 Access denied for user 'root'@'localhost' (using password: YES)

**Comment by itshu** [comment]
前端地址：https://github.com/itshu/vue-admin.git

**Comment by pengxiaolinag** [comment]
同求作者加上前端页面

**Comment by qq53182347** [comment]
已经提供,有需要的自己下载
