### ISSUE TITLE
登录异常

### ISSUE THREAD

**Issue by weiweipang** [qq53182347/liugh-parent#22]
![图片](https://user-images.githubusercontent.com/40154054/60251323-eacc1500-98fa-11e9-8b70-01373b99d5f2.png)

**Comment by weiweipang** [comment]
用post请求
![图片](https://user-images.githubusercontent.com/40154054/60253442-bfe3c000-98fe-11e9-94cb-b6102219c70c.png)

**Comment by eason1314** [comment]
使用post请求，还要在Body里添加参数mobile和password
<img width="693" alt="2019-07-06_202458" src="https://user-images.githubusercontent.com/37476922/60756112-346bdc80-a02c-11e9-8e52-a3eb8ded9d3c.png">

**Comment by qq53182347** [comment]
用json的方式-
