### ISSUE TITLE
shiro-spring

### ISSUE THREAD

**Issue by Asonxw** [qq53182347/liugh-parent#38]
配置shiro-spring的时候，使用@RequiresPermissions注释controller，全部请求都404了，这个怎么解决，搞了一天了还是没办法，求助~~

**Comment by smiledouble** [comment]
@RequiresPermissions这些注解是方法注解把，不要加在类上，还有你可以在shiro的验证方法打断点 看看原因

**Comment by qq53182347** [comment]
权限控制是方法级别的
