### ISSUE TITLE
任何一个接口都要去shiro里面走一遍认证方法吗

### ISSUE THREAD

**Issue by CurtainRight** [qq53182347/liugh-parent#4]
![image](https://user-images.githubusercontent.com/32890541/41768581-35e270be-763f-11e8-8891-9ff159fda140.png)

**Comment by qq53182347** [comment]
对,只有加@Pass的不用,在preHandle方法里直接返回true了.

**Comment by CurtainRight** [comment]
感觉没必要啊，应该一次认证啊。而且这样当请求量大的时候，每次都去走一次shiro认证，走数据库，很好性能啊
