### ISSUE TITLE
不能正确访问登陆接口  返回token

### ISSUE THREAD

**Issue by evanChen63** [qq53182347/liugh-parent#41]
请求登陆接口  一直返回这个信息 {
    "code": "Bad Request",
    "message": "获取登录用户信息失败",
    "status": 400
}

**Comment by evanChen63** [comment]
已解决

**Comment by joelongLin** [comment]
请问怎么解决

**Comment by evanChen63** [comment]
> 请问怎么解决

我记得应该是调整下shiro配置过滤器那里  把login拦截了

**Comment by joelongLin** [comment]
好的，十分感谢
