### ISSUE TITLE
JwtFilter#responseError方法 java.lang.IllegalStateException: getWriter() has already been called for this response

### ISSUE THREAD

**Issue by zhongzhex** [qq53182347/liugh-parent#44]

**Comment by 1750777402** [comment]
大概是因为你使用了SecurityUtils.getSubject().getPrincipal();  这里作者的Realm里面doGetAuthenticationInfo方法return new SimpleAuthenticationInfo(token, token, this.getName()) 构造参数不明白为什么传两个token  其实第一个参数传user进去 就可以SecurityUtils.getSubject().getPrincipal();获取当前登录用户信息了  而且里面setCurrentUser也没必要再去查一次service

**Comment by qq53182347** [comment]
已优化setCurrentUser 查询数据库
